Pool Mining
tari-labs/tari-university pull request #265
Opened 2020-10-21 15:49 UTC by StriderDM

Added Mining.
Moved Merged Mining into Mining.
Added Pool Mining into Mining.
Added Monero Merged Mining into Mining.

2021-05-17 06:45 UTC, hansieodendaal requested changes
Hi @StriderDM,

Please see the comments below.

Thanks.

2021-05-17 06:45 UTC, hansieodendaal commented on src/SUMMARY.md
> +    - [Pools](./mining/pool-mining/pool-mining.md)
**Structure**
- Please collapse 5.1 so that 5.1.1 becomes 5.1 again, 5.1.2 becomes 5.2 and 5.2 becomes 5.3
- - Please add the introduction in `mining.md` to the original `merged-mining.md`

2021-05-17 06:45 UTC, hansieodendaal commented on src/mining/merged-mining-monero/merged-mining-monero.md
> +- [The Process](#the-process)
- Missing **References** from the index
- Missing **Contributors** from the index and the document

2021-05-17 06:45 UTC, hansieodendaal commented on src/mining/merged-mining-monero/merged-mining-monero.md
> +stateDiagram
`stateDiagram` does not render in mdbook

2021-05-17 06:45 UTC, hansieodendaal commented on src/mining/pool-mining/pool-mining.md
> +- [Stratum Mining](#calculating-rewards)
- Missing **References** from the index
- Missing **Contributors** from the index and the document

2021-08-16 11:09 UTC, CjS77 commented
Going to merge this as is, since the site is undergoing a refresh anyways. Content looks ok.

2021-08-16 11:09 UTC, merged